---

- hosts: all
  become: true
  tasks:
  - name: update/upgrade indices
    tags: always
    apt:
      update_cache: yes
      # upgrade: dist
    when: ansible_os_family in ["Debian"]

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php package
    tags: apache,apache2,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php 
      state: latest
    when: ansible_os_family in ["Debian"]
  
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: mqtt_servers
  become: true
  tasks:
  - name: install mqtt server on debian based system
    tags: mqtt,debian
    apt:
      name: mosquitto
      state: present
    when: ansible_os_family in ["Debian"]
